### PR TITLE
Feature/unit tests

### PR DESCRIPTION
**Pull request by erlswtshrt**
Added mocha tests for individual tokens/icons:

- Compares color, size, and font-size tokens to objective-C output
- Compares icons in asset dir to objective-C output

To run: `npm start`

### CODE REVIEW

**Review by ivanbogdanov — CHANGES_REQUESTED** [review]
No need for fonts in this PR

**Comment by erlswtshrt** [comment]
@ivanbogdanov the fonts should be checked in because we want iOS devs to be able to use the library out of the box without rebuilding, so the .ttfs should remain, correct(?).

**Comment by ivanbogdanov** [comment]
Font changes are not part of this PR: any PR should be very focused.

**Comment by jandolina** [comment]
Opened a new PR for this without the fonts

**Pull request closed without merging**
