### PR TITLE
Added bounds checks

### PR DESCRIPTION
**Pull request by jandolina**
This adds more testability to the library. It is for the case when integers are passed to the library instead of enums

@ivanbogdanov @erlswtshrt

### CODE REVIEW

**Review by ivanbogdanov — CHANGES_REQUESTED** [review]
no need for fonts in the PR

**Comment by jandolina** [comment]
Thank you for the PR review. Each time we run the gulp scripts, the icon
fonts get regenerated. That is why they keep showing up in the checkins. I
am unsure how to remove the files from the PR, do either of you guys know?

**Comment by ivanbogdanov** [comment]
Just revert this files and push to the branch you submitted this PR

**Comment by ivanbogdanov** [comment]
It might be cleaner / easier to use forks for PRs

**Pull request closed without merging**
